import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import LenisProvider from "@/components/lenisProvider";
import { PrimeReactProvider } from "primereact/api";
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import 'swiper/css/autoplay';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Raleway({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} overflow-x-hidden`}
      >
        <PrimeReactProvider>
          <LenisProvider>
            {children}
          </LenisProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
